language: python
dist: xenial
python:
  - "3.7"
install:
  - pip install -e ".[dev]"
before_install:
  - sudo su postgres -c $'psql -c "ALTER SYSTEM SET wal_level = \'logical\'"'
  - sudo su postgres -c $'psql -c "ALTER SYSTEM SET max_replication_slots = 10;"'
  - sudo /etc/init.d/postgresql restart 10
  - pip install twine
script:
  - sudo su postgres -c "psql -c 'CREATE DATABASE src;'"
  - sudo su postgres -c "psql -c 'CREATE DATABASE dest;'"
  - sudo su postgres -c "psql src -c 'CREATE TABLE test (id serial);'"
  - sudo su postgres -c "psql dest -c 'CREATE TABLE test (id bigserial);'"
  - python -m pglogicalmanager version
  - python -m pglogicalmanager configure --source=postgres://localhost:5432/src --destination=postgres://localhost:5432/dest
  - python -m pglogicalmanager list-subscriptions
  - python -m pglogicalmanager list-tables --source
  - python -m pglogicalmanager list-tables --destination
  - python -m pglogicalmanager list-columns test --source
  - python -m pglogicalmanager list-columns test --destination
  - python -m pglogicalmanager create-subscription test_sub
  - python -m pglogicalmanager list-subscriptions
  - python -m pglogicalmanager disable-subscription test_sub
  - python -m pglogicalmanager enable-subscription test_sub
  - python -m pglogicalmanager drop-subscription test_sub
  - python -m pglogicalmanager create-replication-slot test_slot
  - python -m pglogicalmanager drop-replication-slot test_slot
  - python -m pglogicalmanager create-replication-slot test_slot
  - python -m pglogicalmanager create-subscription test_sub --replication-slot=test_slot
  - python -m pglogicalmanager list-subscriptions
  - python -m pglogicalmanager drop-subscription test_sub
  - pytest
  - python setup.py sdist bdist_wheel
  - twine check dist/*

addons:
  postgresql: "10"
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10
