language: python
dist: xenial
python:
  - "3.7"
install:
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt
before_install:
  - sudo su postgres -c $'psql -c "ALTER SYSTEM SET wal_level = \'logical\'"'
  - sudo su postgres -c $'psql -c "ALTER SYSTEM SET max_replication_slots = 10;"'
  - sudo /etc/init.d/postgresql restart 10

  # Start second instance of Postgres
  - sudo mkdir /var/lib/postgresql2 && sudo chown postgres:postgres /var/lib/postgresql2
  - ls /usr/lib/postgresql
  - ls /usr/lib/postgresql/10
  - sudo su postgres -c '/usr/lib/postgresql/10/bin/initdb -D /var/lib/postgresql2'
  - sudo su postgres -c '/usr/lib/postgresql/10/bin/pg_ctl -D /var/lib/postgresql2 -o "-p 5433" -l /var/log/postgresql2.log'
script:
  - sudo su postgres -c "psql -c 'CREATE DATABASE src;'"
  - sudo su postgres -c "psql -c 'CREATE DATABASE dest;'"
  - sudo su postgres -c "psql src -c 'CREATE TABLE test (id serial);'"
  - sudo su postgres -c "psql dest -c 'CREATE TABLE test (id bigserial);'"
  - python -m pglogicalmanager configure --source=postgres://localhost:5432/src --destination=postgres://localhost:5432/dest
  - python -m pglogicalmanager list-subscriptions
  - python -m pglogicalmanager list-tables --source
  - python -m pglogicalmanager list-tables --destination
  - python -m pglogicalmanager list-columns test --source
  - python -m pglogicalmanager list-columns test --destination
  - python -m pglogicalmanager create-subscription test_sub
  - python -m pglogicalmanager list-subscriptions
  - python -m pglogicalmanager disable-subscription test_sub
  - python -m pglogicalmanager enable-subscription test_sub
  - python -m pglogicalmanager drop-subscription test_sub
  - python -m pglogicalmanager create-replication-slot test_slot
  - python -m pglogicalmanager drop-replication-slot test_slot
  - pytest

addons:
  postgresql: "10"
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10
