language: python
dist: bionic
python:
  - "3.7"
install:
  - pip install -r requirements.txt
# before_install:
  # - sudo service postgresql start
  # - sudo su postgres -c $'psql -c "ALTER SYSTEM SET wal_level = \'logical\'"'
  # - sudo service postgresql stop
  # - sudo service postgresql start
script:
  - sudo su postgres -c "psql -c 'CREATE DATABASE src;'"
  - sudo su postgres -c "psql -c 'CREATE DATABASE dest;'"
  - sudo su postgres -c "psql src -c 'CREATE TABLE test (id serial);'"
  - sudo su postgres -c "psql dest -c 'CREATE TABLE test (id bigserial);'"
  - python manager.py configure --source=postgres://localhost:5432/src --destination=postgres://localhost:5432/dest
  - python manager.py list-subscriptions
  - python manager.py list-tables --source
  - python manager.py list-tables --destination
  - python manager.py list-columns test --source
  - python manager.py list-columns test --destination
  # - python manager.py create-subscription test_sub
  # - python manager.py list-subscriptions
  # - python manager.py disable-subscription test_sub
  # - python manager.py enable-subscription test_sub
  # - python manager.py drop-subscription test_sub
  # TODO: Figure out why Travis container stalls on restarts when wal_level is changed to logical.
services:
  - postgresql
